name: "Push containers to Docker Hub on release"

on:
  push:
    tags:
      - '*.*.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup environment
        run: cp .env.example .env

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push the backend container
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./prod.Dockerfile
          target: backend
          push: true
          platforms: |
            linux/amd64
            linux/arm64
          tags: |
            xbeeant/hoppscotch_backend:latest
            xbeeant/hoppscotch_backend:${{ github.ref_name }}

      - name: Build and push the frontend container
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./prod.Dockerfile
          target: app
          push: true
          platforms: |
            linux/amd64
            linux/arm64
          tags: |
            xbeeant/hoppscotch_frontend:latest
            xbeeant/hoppscotch_frontend:${{ github.ref_name }}

      - name: Build and push the admin dashboard container
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./prod.Dockerfile
          target: sh_admin
          push: true
          platforms: |
            linux/amd64
            linux/arm64
          tags: |
            xbeeant/hoppscotch_sh_admin:latest
            xbeeant/hoppscotch_sh_admin:${{ github.ref_name }}

      - name: Build and push the AIO container
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./prod.Dockerfile
          target: aio
          push: true
          platforms: |
            linux/amd64
            linux/arm64
          tags: |
            xbeeant/hoppscotch_aio:latest
            xbeeant/hoppscotch_aio:${{ github.ref_name }}
